version: "3.8"
services:
  # Web Server Service
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - ui
    networks:
      - starter_networks
  # UI Service
  ui:
    container_name: ${PROJECT_NAME}-ui
    build:
      dockerfile: Dockerfile.ui
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST}
    volumes:
      - ./src/ui:/var/www/ui
      - /var/www/ui/node_modules
      - /var/www/ui/.next
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - starter_networks

networks:
  starter_networks:
